export type Beatmap = {
    detail?: any,
    error?: string,

    set_id: number,
    map_id: number,
    map_md5: string,
    title: string,
    version: string,
    artist: string,
    creator: string,
    creator_id: number,
    stars: number,
    od: number,
    ar: number,
    cs: number,
    hp: number,
    mode: number,
    bpm: number,
    max_combo: number,
    submit_date: number,
    hit_length: number,
    drain: number,
    plays: number,
    passes: number,
    approved: number,
}